// O'zbekiston hududlari — zal manzilini tanlash uchun.
// Ro'yxat ilovaning ichida turadi (internet kerak emas).
// Tumanlar ro'yxati to'liq bo'lmasligi mumkin — shuning uchun har joyda
// "Boshqa…" varianti bor, u qo'lda yozish maydonini ochadi.

/// Hozircha bitta mamlakat; keyin qo'shilsa shu ro'yxatga yoziladi
const countries = ["O'zbekiston"];

/// Viloyat (yoki respublika / shahar) -> tumanlar
const regions = <String, List<String>>{
  'Toshkent shahri': [
    'Bektemir',
    'Chilonzor',
    'Mirobod',
    "Mirzo Ulug'bek",
    'Olmazor',
    'Sergeli',
    'Shayxontohur',
    'Uchtepa',
    'Yakkasaroy',
    'Yangihayot',
    'Yashnobod',
    'Yunusobod',
  ],
  'Toshkent viloyati': [
    'Angren',
    'Bekobod',
    "Bo'ka",
    "Bo'stonliq",
    'Chinoz',
    'Chirchiq',
    'Nurafshon',
    'Ohangaron',
    "Oqqo'rg'on",
    'Olmaliq',
    'Parkent',
    'Piskent',
    'Qibray',
    'Quyichirchiq',
    "O'rtachirchiq",
    "Yangiyo'l",
    'Yuqorichirchiq',
    'Zangiota',
  ],
  'Andijon': [
    'Andijon shahri',
    'Asaka',
    'Baliqchi',
    "Bo'ston",
    'Buloqboshi',
    'Izboskan',
    'Jalaquduq',
    'Marhamat',
    "Oltinko'l",
    'Paxtaobod',
    "Qo'rg'ontepa",
    'Shahrixon',
    "Ulug'nor",
    'Xonobod',
    "Xo'jaobod",
  ],
  'Buxoro': [
    'Buxoro shahri',
    "G'ijduvon",
    'Jondor',
    'Kogon',
    'Olot',
    'Peshku',
    "Qorako'l",
    'Qorovulbozor',
    'Romitan',
    'Shofirkon',
    'Vobkent',
  ],
  "Farg'ona": [
    "Farg'ona shahri",
    "Marg'ilon",
    "Qo'qon",
    'Quvasoy',
    'Beshariq',
    "Bog'dod",
    'Buvayda',
    "Dang'ara",
    'Furqat',
    'Oltiariq',
    "Qo'shtepa",
    'Quva',
    'Rishton',
    "So'x",
    'Toshloq',
    "Uchko'prik",
    "O'zbekiston tumani",
    'Yozyovon',
  ],
  'Jizzax': [
    'Jizzax shahri',
    'Arnasoy',
    'Baxmal',
    "Do'stlik",
    'Forish',
    "G'allaorol",
    "Mirzacho'l",
    'Paxtakor',
    'Sharof Rashidov',
    'Yangiobod',
    'Zafarobod',
    'Zomin',
  ],
  'Namangan': [
    'Namangan shahri',
    'Chortoq',
    'Chust',
    'Kosonsoy',
    'Mingbuloq',
    'Norin',
    'Pop',
    "To'raqo'rg'on",
    "Uchqo'rg'on",
    'Uychi',
    "Yangiqo'rg'on",
  ],
  'Navoiy': [
    'Navoiy shahri',
    'Zarafshon',
    'Karmana',
    'Konimex',
    'Navbahor',
    'Nurota',
    'Qiziltepa',
    'Tomdi',
    'Uchquduq',
    'Xatirchi',
  ],
  'Qashqadaryo': [
    'Qarshi shahri',
    'Shahrisabz',
    'Chiroqchi',
    'Dehqonobod',
    "G'uzor",
    'Kasbi',
    'Kitob',
    'Koson',
    'Mirishkor',
    'Muborak',
    'Nishon',
    'Qamashi',
    "Yakkabog'",
  ],
  "Qoraqalpog'iston": [
    'Nukus shahri',
    'Amudaryo',
    'Beruniy',
    'Chimboy',
    "Ellikqal'a",
    'Kegeyli',
    "Mo'ynoq",
    "Qanliko'l",
    "Qo'ng'irot",
    "Qorao'zak",
    'Shumanay',
    "Taxtako'pir",
    "To'rtko'l",
    "Xo'jayli",
  ],
  'Samarqand': [
    'Samarqand shahri',
    "Kattaqo'rg'on",
    "Bulung'ur",
    'Ishtixon',
    'Jomboy',
    'Narpay',
    'Nurobod',
    'Oqdaryo',
    "Pastdarg'om",
    'Paxtachi',
    'Payariq',
    "Qo'shrabot",
    'Toyloq',
    'Urgut',
  ],
  'Sirdaryo': [
    'Guliston',
    'Shirin',
    'Yangiyer',
    'Boyovut',
    'Mirzaobod',
    'Oqoltin',
    'Sardoba',
    'Sayxunobod',
    'Sirdaryo tumani',
    'Xovos',
  ],
  'Surxondaryo': [
    'Termiz shahri',
    'Angor',
    'Bandixon',
    'Boysun',
    'Denov',
    "Jarqo'rg'on",
    'Muzrabot',
    'Oltinsoy',
    'Qiziriq',
    "Qumqo'rg'on",
    'Sariosiyo',
    'Sherobod',
    "Sho'rchi",
    'Uzun',
  ],
  'Xorazm': [
    'Urganch shahri',
    'Xiva',
    "Bog'ot",
    'Gurlan',
    'Hazorasp',
    'Xonqa',
    "Qo'shko'pir",
    'Shovot',
    "Tuproqqal'a",
    'Yangiariq',
    'Yangibozor',
  ],
};

/// "Boshqa…" — ro'yxatda yo'q tumanni qo'lda yozish uchun
const otherOption = 'Boshqa…';

/// Viloyat nomlari (ro'yxat tartibida)
List<String> get regionNames => regions.keys.toList();

/// Shu viloyatning tumanlari + "Boshqa…"
List<String> districtsOf(String region) => [...?regions[region], otherOption];
